Fix docs and small edits
JuliaSmoothOptimizers/BenchmarkProfiles.jl pull request #71
Opened 2021-12-22 16:20 UTC by tmigot

The Julia codes for adding a new backend were broken.

2021-12-23 12:16 UTC, abelsiqueira requested changes
Thanks for the update. I've noticed the function were not following our style, so I've suggested these changes.

2021-12-23 12:16 UTC, abelsiqueira commented on docs/src/index.md
> +  end
```suggestion
  function performance_profile_plot(
      ::SomeNewPlotBackend,
      x_plot,
      y_plot,
      max_ratio,
      xlabel,
      ylabel,
      labels,
      title,
      logscale;
      kwargs...
  )
    #
    # now produce the plot and return the plot object
    #
  end
```
To follow our style.

2021-12-23 12:16 UTC, abelsiqueira commented on docs/src/index.md
> +                             kwargs...)
Same here.

2021-12-23 13:54 UTC, tmigot commented on docs/src/index.md
> +                             kwargs...)
Done. Thanks for the comments.

2021-12-23 14:00 UTC, abelsiqueira approved these changes

2021-12-24 03:32 UTC, merged

2021-12-24 03:32 UTC, dpo commented
thank you